
name: 🧪 Test

on:
  push:

jobs:
  test-server:
    name: Run server unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v3

      - name: ⏬ Install dependencies
        run: |
          pip install .[test]

      - name: ✅ Run tests
        run: |
          pytest test
          
